services:
  - type: web
    name: eval-rails
    env: docker
    plan: free
    region: oregon
    buildCommand: ./bin/rails assets:precompile && ./bin/rails db:migrate && ./bin/rails db:seed
    startCommand: ./bin/rails server -b 0.0.0.0
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: GEMINI_API_KEY
        sync: false
